name: Publish Docker Images

on:
  push:
    tags: ['**', '!v*']

jobs:
  build-image:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
      with:
        submodules: true

    - name: Set Metadata
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: rockstorm/bash-ci-server
        tags: |
          type=semver,pattern={{raw}},priority=1000
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: 'rockstorm'
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and Push
      uses: docker/build-push-action@v4
      with:
        context: .
        platforms: |
          linux/386
          linux/amd64
          linux/arm/v6
          linux/arm/v7
          linux/arm64/v8
          linux/ppc64le
          linux/s390x
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
